name          'luismayta-vim'
version       '0.1.0'
source        ''
author        'luis mayta'
license       'Apache 2.0'
summary       ''
description   ''
project_page  ''

dependency 'puppetlabs/stdlib'
